# Generated by Django 4.2.6 on 2023-10-15 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
                ('titulo', models.CharField(max_length=100)),
                ('descrição', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('ANALISES', 'Ánalises'), ('PROGRAMACAO', 'Programacao'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros')], max_length=15)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criação', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
