# Generated by Django 4.2.6 on 2023-10-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_seriados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seriados',
            new_name='Seriado',
        ),
    ]
