# Generated by Django 4.2.4 on 2023-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('MASCULIO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=8),
        ),
    ]
